baseurl: '/'
permalink: pretty
title: 'Glasses Web'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.png"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_services: 7

collections:
  products:
    output: true
  news:
    output: true
  jobs:
    output: true
  reviews:
    output: true

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
      type: "news"
    values:
      layout: "news"
  - scope:
      path: ""
      type: "jobs"
    values:
      layout: "jobs"
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "review"
            
sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
